### ISSUE TITLE
HCL should be UCL?

### ISSUE THREAD

**Issue by ikolomi** [riboseinc/libnereon#36]
This library parses the following configurations by HCL. -> Should be universal configuration language?
@jjr840430 @ronaldtse

**Comment by jjr840430** [comment]
Yes, but it's possible to parse JSON configurations too.

**Comment by ronaldtse** [comment]
Nereon syntax is described here https://github.com/riboseinc/nereon-syntax

Nereon is different from libucl (which is more generic) but more generic than HCL, and supports additional features such as interpolation and various data types.

**Comment by ikolomi** [comment]
What I meant is - isn’t HCL a typo? What does it stands for? I know what
UCL is, but what is HCL?

**Comment by ronaldtse** [comment]
HCL is https://www.github.com/hashicorp/hcl

**Comment by ikolomi** [comment]
@ronaldtse  Thanks, closing issue
