### ISSUE TITLE
HCL doesn’t exist, is it supposed to be UCL?

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/libnereon#37]
Docs [refer to](https://github.com/riboseinc/libnereon#introduction) HCL, but linked site refers to UCL. Perhaps the maintainer renamed it?

**Comment by jjr840430** [comment]
HCL is [here]<https://github.com/hashicorp/hcl>.
You can read the following line there.

```
HCL is heavily inspired by [libucl]<https://github.com/vstakhov/libucl>, nginx configuration, and others similar.
```

**Comment by strogonoff** [comment]
@jjr840430 Does libnereon parse HCL or UCL? Yeah I know they are related but they are not the same thing.

**Comment by ronaldtse** [comment]
Libnereon parses “Nereon Syntax”. It was inspired by HCL and UCL, which was inspired by JSON and nginx configuration syntax.

**Comment by strogonoff** [comment]
@ronaldtse could you clarify what this part of README means?

> `libnereon` is a multi-configuration parser library implemented in C.</br>
> This library parses the following configurations by [HCL](https://github.com/vstakhov/libucl).
> 
>  * The command-line arguments.
>  * The environment variables.
>  * The configuration files.

The linked page has no mention of command-line argument, environment variables, configuration files or HCL. What is the intended link target?

**Comment by strogonoff** [comment]
@drystone’s [answer](https://github.com/riboseinc/nereon.com/issues/1#issuecomment-421433065) covered it, I might make a PR to update README later!
