### ISSUE TITLE
LIBNEREON_LIBRARY is not defined as CMake target

### ISSUE THREAD

**Issue by maxirmx** [riboseinc/libnereon#40]
There is a problem here: https://github.com/riboseinc/libnereon/blob/master/src/CMakeLists.txt

LIBNEREON_LIBRARY is not defined as CMake target at all.  Unix and MacOS versions of cmake somehow manage to create correct build sequence, but MSYS  version fails.  So the fix is required at libneron source.

_Originally posted by @maxirmx in https://github.com/riboseinc/retrace/issues/421#issuecomment-1010381327_

**Comment by ronaldtse** [comment]
@maxirmx thanks for reporting this. Would you be able to help fix this? Thanks!
