### ISSUE TITLE
Add GHA build workflows for macOS, Ubuntu and Windows

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/libnereon#42]

**Comment by ronaldtse** [comment]
And remove .travis.yml:
https://github.com/riboseinc/libnereon/blob/5d4c09b30b9b758a37fa01cb739b20a138ca5aec/.travis.yml#L1-L12

**Comment by maxirmx** [comment]
WIndows (MSYS) is there: https://github.com/riboseinc/libnereon/pull/41
